# Generated by Django 5.0.6 on 2024-06-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_file', models.ImageField(blank=True, upload_to='med_files', verbose_name='Файл')),
                ('description', models.TextField(verbose_name='Описание мед.файла')),
            ],
        ),
        migrations.CreateModel(
            name='PetProfiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=255, verbose_name='Имя питомца')),
                ('age', models.IntegerField(verbose_name='Возраст питомца')),
                ('json_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PetTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(max_length=256, unique=True, verbose_name='Тип питомца')),
            ],
        ),
    ]
