# Generated by Django 5.0.6 on 2024-06-27 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofiles',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
    ]
