# Generated by Django 5.0.6 on 2024-06-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0003_alter_petprofiles_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofiles',
            name='json_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
