# Generated by Django 5.0.6 on 2024-06-27 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_profile', '0004_alter_petprofiles_json_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medfiles',
            options={'verbose_name': 'Мед.файл', 'verbose_name_plural': 'Мед.файлы'},
        ),
        migrations.AlterModelOptions(
            name='petprofiles',
            options={'verbose_name': 'Профиль питомца', 'verbose_name_plural': 'Профили питомцев'},
        ),
        migrations.AlterModelOptions(
            name='pettypes',
            options={'verbose_name': 'Тип питомца', 'verbose_name_plural': 'Тип питомца'},
        ),
        migrations.AlterField(
            model_name='petprofiles',
            name='pet_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_profile.pettypes'),
        ),
    ]
