# Generated by Django 5.0.6 on 2024-06-27 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pet_calendar', '0001_initial'),
        ('pet_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarrecords',
            name='pet_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_profile.petprofiles'),
        ),
        migrations.AddField(
            model_name='calendarrecords',
            name='procedure_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_calendar.proceduretypes'),
        ),
    ]
