# Generated by Django 5.0.6 on 2024-06-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_calendar', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceduretypes',
            name='description',
        ),
        migrations.AddField(
            model_name='calendarrecords',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание процедуры'),
        ),
        migrations.AddField(
            model_name='calendarrecords',
            name='json_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
