# Generated by Django 5.0.6 on 2024-06-27 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_calendar', '0003_remove_proceduretypes_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarrecords',
            options={'verbose_name': 'Запись в календаре', 'verbose_name_plural': 'Записи в календаре'},
        ),
        migrations.AlterModelOptions(
            name='proceduretypes',
            options={'verbose_name': 'Процедура', 'verbose_name_plural': 'Процедуры'},
        ),
    ]
