# Generated by Django 5.0.6 on 2024-06-27 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_calendar', '0004_alter_calendarrecords_options_and_more'),
        ('pet_profile', '0006_alter_medfiles_pet_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarrecords',
            name='pet_profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_profile.petprofiles', verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='calendarrecords',
            name='procedure_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_calendar.proceduretypes', verbose_name='Тип процедуры'),
        ),
    ]
