# Generated by Django 5.0.6 on 2024-07-08 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_calendar', '0005_alter_calendarrecords_pet_profile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Описание процедуры')),
                ('procedure_date', models.DateTimeField(verbose_name='Дата и время процедуры')),
                ('json_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Запись в календаре',
                'verbose_name_plural': 'Записи в календаре',
            },
        ),
        migrations.CreateModel(
            name='ProcedureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип процедуры')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
        migrations.RemoveField(
            model_name='calendarrecords',
            name='pet_profile_id',
        ),
        migrations.RemoveField(
            model_name='calendarrecords',
            name='procedure_type_id',
        ),
    ]
