# Generated by Django 5.0.6 on 2024-07-08 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_calendar', '0006_calendarrecord_proceduretype_and_more'),
        ('pet_profile', '0007_pettype_remove_petprofiles_pet_type_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarrecord',
            name='pet_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet_profile.petprofile', verbose_name='Питомец'),
        ),
        migrations.AddField(
            model_name='calendarrecord',
            name='procedure_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet_calendar.proceduretype', verbose_name='Тип процедуры'),
        ),
        migrations.DeleteModel(
            name='CalendarRecords',
        ),
        migrations.DeleteModel(
            name='ProcedureTypes',
        ),
    ]
