# Generated by Django 5.0.6 on 2024-07-08 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_alter_encyclopediarecords_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncyclopediaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание статьи')),
                ('full_text', models.TextField(verbose_name='Текст статьи')),
                ('image', models.ImageField(upload_to='article_files', verbose_name='Картинка')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='encyclopedia.encyclopediarecord', verbose_name='Родительская статья')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.DeleteModel(
            name='EncyclopediaRecords',
        ),
    ]
